# Generated by Django 5.2 on 2025-08-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('INIT', 'init'), ('IN_PROGRESS', 'in_progress'), ('FINISHED', 'finished')], default='init', max_length=200),
        ),
    ]
