# Generated by Django 5.2 on 2025-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_athleteinfo_goals_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
