# Generated by Django 5.2 on 2025-08-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
