# Generated by Django 5.2 on 2025-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position_id_alter_position_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
