# Generated by Django 5.2 on 2025-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_alter_position_latitude_alter_position_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
